#server
server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    max-threads: 1000

#spring
spring:
  datasource:
    url: jdbc:mysql:///jwd?serverTimezone=GMT
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/pages/
    suffix: .html
   
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

#mybatis
mybatis-plus: 
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:/mapper/*.xml

#lOG
logging:
  level: 
    cn.jwd: DEBUG
